[INFO] W&B run initialized successfully
train at epoch 1
train at epoch 1
/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/nn/functional.py:652: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)
Epoch: [1][0/194]	 lr: 0.04000	Time 42.582 (42.582)	Data 11.551 (11.551)	Loss 2.1034 (2.1034)	Prec@1 0.00000 (0.00000)	Prec@5 71.87500 (71.87500)
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fedf6133160>
Traceback (most recent call last):
  File "/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1327, in __del__
    def __del__(self):
  File "/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13605) is killed by signal: Killed.
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    log = train_epoch(i, train_loader, model, criterion, optimizer, opt,
  File "/home/dmura/baseline-modal/train.py", line 121, in train_epoch
    log = train_epoch_multimodal(epoch,  data_loader, model, criterion, optimizer, opt, epoch_logger, batch_logger)
  File "/home/dmura/baseline-modal/train.py", line 73, in train_epoch_multimodal
    loss.backward()
  File "/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/dmura/anaconda3/envs/idl-baseline-env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: [enforce fail at CPUAllocator.cpp:71] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 180633600 bytes. Error code 12 (Cannot allocate memory)